// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.query.sql

package DB

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const enrollStudent = `-- name: EnrollStudent :exec
INSERT INTO course_enrollments (
    user_id,
    course_id
) VALUES ($1, $2)
`

type EnrollStudentParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) EnrollStudent(ctx context.Context, arg EnrollStudentParams) error {
	_, err := q.db.Exec(ctx, enrollStudent, arg.UserID, arg.CourseID)
	return err
}

const getCourseLessons = `-- name: GetCourseLessons :many
SELECT
    s.section_id,
    s.title AS section_title,
    l.lesson_id,
    l.title AS lesson_title
FROM sections s
JOIN lessons l
ON l.section_id = s.section_id
WHERE s.course_id = $1
ORDER BY s.position, l.position
`

type GetCourseLessonsRow struct {
	SectionID    uuid.UUID `json:"section_id"`
	SectionTitle string    `json:"section_title"`
	LessonID     uuid.UUID `json:"lesson_id"`
	LessonTitle  string    `json:"lesson_title"`
}

func (q *Queries) GetCourseLessons(ctx context.Context, courseID uuid.UUID) ([]GetCourseLessonsRow, error) {
	rows, err := q.db.Query(ctx, getCourseLessons, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseLessonsRow
	for rows.Next() {
		var i GetCourseLessonsRow
		if err := rows.Scan(
			&i.SectionID,
			&i.SectionTitle,
			&i.LessonID,
			&i.LessonTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseStudents = `-- name: GetCourseStudents :many
SELECT
    u.id,
    u.name,
    u.email,
    ce.enrolled_at
FROM users u
JOIN course_enrollments ce
ON ce.user_id = u.id
WHERE ce.course_id = $1
`

type GetCourseStudentsRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	EnrolledAt time.Time `json:"enrolled_at"`
}

func (q *Queries) GetCourseStudents(ctx context.Context, courseID uuid.UUID) ([]GetCourseStudentsRow, error) {
	rows, err := q.db.Query(ctx, getCourseStudents, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseStudentsRow
	for rows.Next() {
		var i GetCourseStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentCourses = `-- name: GetStudentCourses :many
SELECT
    c.course_id,
    c.title,
    c.description,
    c.creator_id,
    ce.enrolled_at
FROM courses c
JOIN course_enrollments ce
ON ce.course_id = c.course_id
WHERE ce.user_id = $1
ORDER BY ce.enrolled_at DESC
`

type GetStudentCoursesRow struct {
	CourseID    uuid.UUID `json:"course_id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	CreatorID   uuid.UUID `json:"creator_id"`
	EnrolledAt  time.Time `json:"enrolled_at"`
}

func (q *Queries) GetStudentCourses(ctx context.Context, userID uuid.UUID) ([]GetStudentCoursesRow, error) {
	rows, err := q.db.Query(ctx, getStudentCourses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentCoursesRow
	for rows.Next() {
		var i GetStudentCoursesRow
		if err := rows.Scan(
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.CreatorID,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentCoursesWithInstructor = `-- name: GetStudentCoursesWithInstructor :many
SELECT
    c.course_id,
    c.title,
    u.name AS instructor,
    ce.enrolled_at
FROM course_enrollments ce
JOIN courses c
    ON ce.course_id = c.course_id
JOIN users u
    ON u.id = c.creator_id
WHERE ce.user_id = $1
`

type GetStudentCoursesWithInstructorRow struct {
	CourseID   uuid.UUID `json:"course_id"`
	Title      string    `json:"title"`
	Instructor string    `json:"instructor"`
	EnrolledAt time.Time `json:"enrolled_at"`
}

func (q *Queries) GetStudentCoursesWithInstructor(ctx context.Context, userID uuid.UUID) ([]GetStudentCoursesWithInstructorRow, error) {
	rows, err := q.db.Query(ctx, getStudentCoursesWithInstructor, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentCoursesWithInstructorRow
	for rows.Next() {
		var i GetStudentCoursesWithInstructorRow
		if err := rows.Scan(
			&i.CourseID,
			&i.Title,
			&i.Instructor,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isStudentEnrolled = `-- name: IsStudentEnrolled :one
SELECT EXISTS (
    SELECT 1
    FROM course_enrollments
    WHERE user_id = $1
    AND course_id = $2
)
`

type IsStudentEnrolledParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) IsStudentEnrolled(ctx context.Context, arg IsStudentEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isStudentEnrolled, arg.UserID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
