// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package DB

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PasswordResetToken struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
}

type RefreshToken struct {
	TokenID    uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	CreatedAt  time.Time
	Revoked    pgtype.Bool
	ReplacedBy pgtype.UUID
	UserAgent  pgtype.Text
	IpAddress  pgtype.Text
}

type User struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  pgtype.Text
	OauthProvider pgtype.Text
	OauthID       pgtype.Text
	CreatedAt     time.Time
}
