// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package DB

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (
    token_id,
    user_id,
    token_hash,
    expires_at,
    user_agent,
    ip_address
)
VALUES ($1, $2, $3, $4,$5,$6)
`

type CreateRefreshTokenParams struct {
	TokenID   uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UserAgent pgtype.Text
	IpAddress pgtype.Text
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.TokenID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, name, email, password_hash, oauth_provider, oauth_id, created_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllRefreshTokens = `-- name: DeleteAllRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteAllRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokens, userID)
	return err
}

const deleteAllRefreshTokensExcept = `-- name: DeleteAllRefreshTokensExcept :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
AND token_id != $2
`

type DeleteAllRefreshTokensExceptParams struct {
	UserID  uuid.UUID
	TokenID uuid.UUID
}

func (q *Queries) DeleteAllRefreshTokensExcept(ctx context.Context, arg DeleteAllRefreshTokensExceptParams) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokensExcept, arg.UserID, arg.TokenID)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens
WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, userID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM refresh_tokens
WHERE token_id = $1
AND user_id = $2
`

type DeleteSessionParams struct {
	TokenID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.TokenID, arg.UserID)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = $1
) AS exists
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, oauth_provider, oauth_id, created_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, oauth_provider, oauth_id, created_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIDByResetToken = `-- name: GetUserIDByResetToken :one
SELECT user_id FROM password_reset_tokens
WHERE token = $1
AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetUserIDByResetToken(ctx context.Context, token string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByResetToken, token)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT
    token_id,
    user_agent,
    ip_address,
    created_at,
    expires_at
FROM refresh_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetUserSessionsRow struct {
	TokenID   uuid.UUID
	UserAgent pgtype.Text
	IpAddress pgtype.Text
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) GetUserSessions(ctx context.Context, userID uuid.UUID) ([]GetUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSessionsRow
	for rows.Next() {
		var i GetUserSessionsRow
		if err := rows.Scan(
			&i.TokenID,
			&i.UserAgent,
			&i.IpAddress,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTokenExists = `-- name: RefreshTokenExists :one
SELECT EXISTS (
    SELECT 1 FROM refresh_tokens
    WHERE user_id = $1
    AND token_hash = $2
    AND expires_at > NOW()
) AS exists
`

type RefreshTokenExistsParams struct {
	UserID    uuid.UUID
	TokenHash string
}

func (q *Queries) RefreshTokenExists(ctx context.Context, arg RefreshTokenExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, refreshTokenExists, arg.UserID, arg.TokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const upsertOAuthUser = `-- name: UpsertOAuthUser :one
INSERT INTO users (name, email, oauth_provider, oauth_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email)
DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, email, password_hash, oauth_provider, oauth_id, created_at
`

type UpsertOAuthUserParams struct {
	Name          string
	Email         string
	OauthProvider pgtype.Text
	OauthID       pgtype.Text
}

func (q *Queries) UpsertOAuthUser(ctx context.Context, arg UpsertOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertOAuthUser,
		arg.Name,
		arg.Email,
		arg.OauthProvider,
		arg.OauthID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.OauthProvider,
		&i.OauthID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPasswordResetToken = `-- name: UpsertPasswordResetToken :exec
INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id)
DO UPDATE SET
    token = EXCLUDED.token,
    expires_at = EXCLUDED.expires_at
`

type UpsertPasswordResetTokenParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) UpsertPasswordResetToken(ctx context.Context, arg UpsertPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}
